In [3]:
#importing packages and data
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
import pydotplus 
from sklearn import metrics
from sklearn import tree
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.grid_search import GridSearchCV
from sklearn.metrics import classification_report

train_data = pd.read_csv('C:/Users/Megan/Documents/Duke/Thesis/Modeling/train_data.csv')
test_data = pd.read_csv('C:/Users/Megan/Documents/Duke/Thesis/Modeling/test_data.csv')

del train_data['Unnamed: 0']; del test_data['Unnamed: 0']
X_train = train_data.drop('made', axis = 1)
X_test = test_data.drop('made', axis = 1)
Y_train = train_data['made']
Y_test = test_data['made']

np.random.seed(10)

In [5]:
X_train.iloc[0]

accel_changes                   38.000000
closest_def_locleft              0.000000
closest_def_locright             1.000000
closest_defender_angle           0.261488
closest_defender_dist           14.240083
closest_teammate_angle           2.867618
closest_teammate_dist           14.507800
closest_teammate_locleft         0.000000
closest_teammate_locright        1.000000
court_zone                       3.000000
game_clock                   70042.000000
num_close_def                    0.000000
num_close_team                   0.000000
num_poss                         5.000000
other_shot                       1.000000
quarter                          3.000000
shooter_avg_vel                  9.699054
shooter_dist_to_ball             0.760117
shooter_dist_traveled           96.990536
shooter_team                     1.000000
shooter_vel_at_shot             16.300756
shot_clock                      21.990000
shot_val                         3.000000
x_loc                           69

In [41]:
#fitting the decision tree model
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, Y_train)
clf_matrix = confusion_matrix(Y_test, clf.predict(X_test))
print(clf_matrix)

[[707 431]
 [429 396]]


In [44]:
tree.export_graphviz(clf)

In [47]:
#figure generation
dot_data = tree.export_graphviz(clf) 
graph = pydotplus.graph_from_dot_data(dot_data) 
#graph.write_pdf("iris.pdf") 

TypeError: object of type 'NoneType' has no len()

In [4]:
np.random.seed(100)

In [62]:
##random forests
parameters = [{'n_estimators': list(range(25, 201, 25)),
               'max_features': list(range(2, 15, 2))}]
rf = GridSearchCV(RandomForestClassifier(), parameters,
                   cv=5, scoring='accuracy', n_jobs=-1)
rf.fit(X_train, Y_train)
pass

In [63]:
rf.best_params_

{'max_features': 6, 'n_estimators': 150}

In [55]:
rf_matrix = confusion_matrix(Y_test, rf.predict(X_test))
print(rf_matrix)

[[837 301]
 [449 376]]


In [65]:
rf_two = GridSearchCV(RandomForestClassifier(), parameters,
                   cv=5, scoring='accuracy', n_jobs=-1)
rf_two.fit(X_train, Y_train)
pass

print(rf_two.best_params_)
rf_matrix_two = confusion_matrix(Y_test, rf_two.predict(X_test))
print(rf_matrix_two)

[[894 244]
 [496 329]]


In [68]:
print(rf_two.best_params_)

{'max_features': 4, 'n_estimators': 200}


In [67]:
rf_three = GridSearchCV(RandomForestClassifier(), parameters,
                   cv=5, scoring='accuracy', n_jobs=-1)
rf_three.fit(X_train, Y_train)
pass

print(rf_three.best_params_)
rf_matrix_three = confusion_matrix(Y_test, rf_three.predict(X_test))
print(rf_matrix_three)

{'max_features': 14, 'n_estimators': 200}
[[821 317]
 [445 380]]
